import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const fail = [];
const pass = [];

function readJson(rel) {
  return JSON.parse(fs.readFileSync(path.join(root, rel), 'utf8'));
}

function exists(rel) {
  return fs.existsSync(path.join(root, rel));
}

function check(name, ok, detail = '') {
  (ok ? pass : fail).push({ name, ok, detail });
}

function sha256(rel) {
  return crypto.createHash('sha256').update(fs.readFileSync(path.join(root, rel))).digest('hex');
}

function readText(rel) {
  return fs.readFileSync(path.join(root, rel), 'utf8');
}

const pkg = readJson('package.json');
const tauri = readJson('src-tauri/tauri.conf.json');
const cargoToml = readText('src-tauri/Cargo.toml');
const cargoVersion = cargoToml.match(/^version = "([^"]+)"/m)?.[1] || '';
const installer = `src-tauri/target/release/bundle/nsis/Aegos_${pkg.version}_x64-setup.exe`;
const installerSha = exists(installer) ? sha256(installer) : '';
const releaseDoc = `RELEASE_${pkg.version}.md`;
const releaseNotes = exists(releaseDoc) ? readText(releaseDoc) : '';
const sourceOnlyRelease = releaseNotes.includes('Source-only');

check('package name is aegos', pkg.name === 'aegos', pkg.name);
check('package/Tauri/Cargo versions match', pkg.version === tauri.version && pkg.version === cargoVersion, `${pkg.version}/${tauri.version}/${cargoVersion}`);
check('product name is Aegos', tauri.productName === 'Aegos', tauri.productName);
check('identifier does not collide with Aegis', tauri.identifier === 'com.codex.aegos', tauri.identifier);
check('Tauri shell configured', Boolean(pkg.devDependencies?.['@tauri-apps/cli']), '@tauri-apps/cli');
check('transparent window disabled for performance', tauri.app?.windows?.[0]?.transparent === false, `transparent=${tauri.app?.windows?.[0]?.transparent}`);
check('WebView2 missing runtime is handled by installer', tauri.bundle?.windows?.webviewInstallMode?.type === 'downloadBootstrapper' && tauri.bundle?.windows?.webviewInstallMode?.silent === false, JSON.stringify(tauri.bundle?.windows?.webviewInstallMode));
check('mihomo bundled as only core resource', exists('resources/core/mihomo.exe') && !exists('resources/core/sing-box.exe'), 'resources/core');
check('Aegos installer exists or release is source-only', exists(installer) || sourceOnlyRelease, installer);
check('Aegis installer name is not reused', !exists(`src-tauri/target/release/bundle/nsis/Aegis-Setup-${pkg.version}.exe`), 'no Aegis installer artifact');
check('UI smoke script exists', exists('tools/ui-smoke.js'), 'tools/ui-smoke.js');
check('performance smoke script exists', exists('tools/perf-smoke.js') && pkg.scripts?.['smoke:perf'] === 'node tools/perf-smoke.js', 'tools/perf-smoke.js');
check('soak smoke script exists', exists('tools/soak-smoke.js') && pkg.scripts?.['smoke:soak'] === 'node tools/soak-smoke.js', 'tools/soak-smoke.js');
check('global interaction product gate exists', exists('tools/global-interaction-product-audit.js') && pkg.scripts?.['audit:global-interaction-product'] === 'node tools/global-interaction-product-audit.js', 'global interaction product gate');
check('backend audit script exists', exists('tools/backend-audit.js') && pkg.scripts?.['audit:backend'] === 'node tools/backend-audit.js', 'tools/backend-audit.js');
check('security hotfix audit script exists', exists('tools/security-hotfix-audit.js') && pkg.scripts?.['audit:security'] === 'node tools/security-hotfix-audit.js', 'tools/security-hotfix-audit.js');
check('settings security productization gate exists', exists('tools/settings-security-product-audit.js') && pkg.scripts?.['audit:settings-security-product'] === 'node tools/settings-security-product-audit.js', 'settings security productization gate');
check('diagnostics productization gate exists', exists('tools/diagnostics-product-audit.js') && pkg.scripts?.['audit:diagnostics-product'] === 'node tools/diagnostics-product-audit.js', 'diagnostics productization gate');
check('stability regression audit script exists', exists('tools/stability-regression-audit.js') && pkg.scripts?.['audit:stability'] === 'node tools/stability-regression-audit.js', 'tools/stability-regression-audit.js');
check('installer candidate audit script exists', exists('tools/installer-candidate-audit.js') && pkg.scripts?.['audit:installer'] === 'node tools/installer-candidate-audit.js', 'tools/installer-candidate-audit.js');
check('node-flow audit script exists', exists('tools/node-flow-audit.js') && pkg.scripts?.['audit:node-flow'] === 'node tools/node-flow-audit.js', 'node-flow-audit.js');
check('architecture freeze audit script exists', exists('tools/architecture-freeze-audit.js') && pkg.scripts?.['audit:architecture'] === 'node tools/architecture-freeze-audit.js' && exists('ARCHITECTURE_FREEZE_2.9.20_TO_2.9.29.md'), 'tools/architecture-freeze-audit.js / ARCHITECTURE_FREEZE_2.9.20_TO_2.9.29.md');
check('debt audit script exists', exists('tools/debt-audit.js') && pkg.scripts?.['audit:debt'] === 'node tools/debt-audit.js', 'tools/debt-audit.js');
check('opensource absorption audit script exists', exists('tools/opensource-absorption-audit.js') && pkg.scripts?.['audit:opensource'] === 'node tools/opensource-absorption-audit.js' && exists('research/opensource-absorption-standard.md') && exists('research/opensource-reference.md') && exists('research/opensource-absorption-roadmap.md') && exists('core-api-contract.md'), 'tools/opensource-absorption-audit.js / research / core-api-contract.md');
check('FlClash benchmark audit script exists', exists('tools/flclash-benchmark-audit.js') && pkg.scripts?.['audit:flclash'] === 'node tools/flclash-benchmark-audit.js' && exists('research/flclash-benchmark-2.9.54.md'), 'tools/flclash-benchmark-audit.js / research/flclash-benchmark-2.9.54.md');
check('speed target contract audit script exists', exists('tools/speed-target-audit.js') && pkg.scripts?.['audit:speed-target'] === 'node tools/speed-target-audit.js' && exists('speed-target-contract.md'), 'tools/speed-target-audit.js / speed-target-contract.md');
check('provider healthcheck audit script exists', exists('tools/provider-healthcheck-audit.js') && pkg.scripts?.['audit:provider-healthcheck'] === 'node tools/provider-healthcheck-audit.js' && exists('provider-healthcheck-contract.md'), 'tools/provider-healthcheck-audit.js / provider-healthcheck-contract.md');
check('installer regression audit script exists', exists('tools/installer-regression-audit.js') && pkg.scripts?.['audit:installer-regression'] === 'node tools/installer-regression-audit.js' && exists('installer-regression-checklist.md'), 'tools/installer-regression-audit.js / installer-regression-checklist.md');
check('copy encoding audit script exists', exists('tools/copy-encoding-audit.js') && pkg.scripts?.['audit:copy'] === 'node tools/copy-encoding-audit.js' && exists('copy-encoding-debt.md'), 'tools/copy-encoding-audit.js / copy-encoding-debt.md');
check('maturity gate audit script exists', exists('tools/maturity-gate-audit.js') && pkg.scripts?.['audit:maturity'] === 'node tools/maturity-gate-audit.js' && exists('ROADMAP_3.0.0_TO_3.6.4.md'), 'tools/maturity-gate-audit.js / ROADMAP_3.0.0_TO_3.6.4.md');
check('product maturity audit script exists', exists('tools/product-maturity-audit.js') && pkg.scripts?.['audit:product-maturity'] === 'node tools/product-maturity-audit.js' && exists('PRODUCT_MATURITY_RECOVERY_PLAN.md') && exists('PRODUCT_MATURITY_3.4.11_TO_3.4.20_DETAILED.md') && exists('PRODUCT_MATURITY_GAP_REPORT.md'), 'tools/product-maturity-audit.js / PRODUCT_MATURITY_GAP_REPORT.md');
check('connection closure audit script exists', exists('tools/connection-closure-audit.js') && pkg.scripts?.['audit:connection-closure'] === 'node tools/connection-closure-audit.js', 'tools/connection-closure-audit.js');
check('node speed product audit script exists', exists('tools/node-speed-product-audit.js') && pkg.scripts?.['audit:node-speed-product'] === 'node tools/node-speed-product-audit.js', 'tools/node-speed-product-audit.js');
check('subscription product audit script exists', exists('tools/subscription-product-audit.js') && pkg.scripts?.['audit:subscription-product'] === 'node tools/subscription-product-audit.js', 'tools/subscription-product-audit.js');
check('home product audit script exists', exists('tools/home-product-audit.js') && pkg.scripts?.['audit:home-product'] === 'node tools/home-product-audit.js', 'tools/home-product-audit.js');
check('node strategy UI audit script exists', exists('tools/node-strategy-ui-audit.js') && pkg.scripts?.['audit:node-strategy-ui'] === 'node tools/node-strategy-ui-audit.js', 'tools/node-strategy-ui-audit.js');
check('core runtime audit script exists', exists('tools/core-runtime-audit.js') && pkg.scripts?.['audit:core-runtime'] === 'node tools/core-runtime-audit.js', 'tools/core-runtime-audit.js');
check('routing read-only audit script exists', exists('tools/routing-readonly-audit.js') && pkg.scripts?.['audit:routing-readonly'] === 'node tools/routing-readonly-audit.js', 'tools/routing-readonly-audit.js');
check('routing navigation audit script exists', exists('tools/routing-navigation-audit.js') && pkg.scripts?.['audit:routing-navigation'] === 'node tools/routing-navigation-audit.js', 'tools/routing-navigation-audit.js');
check('routing mode audit script exists', exists('tools/routing-mode-audit.js') && pkg.scripts?.['audit:routing-mode'] === 'node tools/routing-mode-audit.js', 'tools/routing-mode-audit.js');
check('routing groups audit script exists', exists('tools/routing-groups-audit.js') && pkg.scripts?.['audit:routing-groups'] === 'node tools/routing-groups-audit.js', 'tools/routing-groups-audit.js');
check('routing types audit script exists', exists('tools/routing-types-audit.js') && pkg.scripts?.['audit:routing-types'] === 'node tools/routing-types-audit.js', 'tools/routing-types-audit.js');
check('routing selection audit script exists', exists('tools/routing-selection-audit.js') && pkg.scripts?.['audit:routing-selection'] === 'node tools/routing-selection-audit.js', 'tools/routing-selection-audit.js');
check('routing redaction audit script exists', exists('tools/routing-redaction-audit.js') && pkg.scripts?.['audit:routing-redaction'] === 'node tools/routing-redaction-audit.js', 'tools/routing-redaction-audit.js');
check('routing acceptance audit script exists', exists('tools/routing-acceptance-audit.js') && pkg.scripts?.['audit:routing-acceptance'] === 'node tools/routing-acceptance-audit.js', 'tools/routing-acceptance-audit.js');
check('routing rules audit script exists', exists('tools/routing-rules-audit.js') && pkg.scripts?.['audit:routing-rules'] === 'node tools/routing-rules-audit.js', 'tools/routing-rules-audit.js');
check('routing targets audit script exists', exists('tools/routing-targets-audit.js') && pkg.scripts?.['audit:routing-targets'] === 'node tools/routing-targets-audit.js', 'tools/routing-targets-audit.js');
check('routing order audit script exists', exists('tools/routing-order-audit.js') && pkg.scripts?.['audit:routing-order'] === 'node tools/routing-order-audit.js', 'tools/routing-order-audit.js');
check('routing profile switch audit script exists', exists('tools/routing-profile-switch-audit.js') && pkg.scripts?.['audit:routing-profile-switch'] === 'node tools/routing-profile-switch-audit.js', 'tools/routing-profile-switch-audit.js');
check('routing reload preflight audit script exists', exists('tools/routing-reload-preflight-audit.js') && pkg.scripts?.['audit:routing-reload-preflight'] === 'node tools/routing-reload-preflight-audit.js', 'tools/routing-reload-preflight-audit.js');
check('routing rollback audit script exists', exists('tools/routing-rollback-audit.js') && pkg.scripts?.['audit:routing-rollback'] === 'node tools/routing-rollback-audit.js', 'tools/routing-rollback-audit.js');
check('routing diagnostics audit script exists', exists('tools/routing-diagnostics-audit.js') && pkg.scripts?.['audit:routing-diagnostics'] === 'node tools/routing-diagnostics-audit.js', 'tools/routing-diagnostics-audit.js');
check('routing foundation audit script exists', exists('tools/routing-foundation-audit.js') && pkg.scripts?.['audit:routing-foundation'] === 'node tools/routing-foundation-audit.js', 'tools/routing-foundation-audit.js');
check('routing assistant gate audit script exists', exists('tools/routing-assistant-gate-audit.js') && pkg.scripts?.['audit:routing-assistant-gate'] === 'node tools/routing-assistant-gate-audit.js', 'tools/routing-assistant-gate-audit.js');
check('routing UX audit script exists', exists('tools/routing-ux-audit.js') && pkg.scripts?.['audit:routing-ux'] === 'node tools/routing-ux-audit.js', 'tools/routing-ux-audit.js');
check('routing app UX audit script exists', exists('tools/routing-app-ux-audit.js') && pkg.scripts?.['audit:routing-app-ux'] === 'node tools/routing-app-ux-audit.js', 'tools/routing-app-ux-audit.js');
check('routing connection draft audit script exists', exists('tools/routing-connection-draft-audit.js') && pkg.scripts?.['audit:routing-connection-draft'] === 'node tools/routing-connection-draft-audit.js', 'tools/routing-connection-draft-audit.js');
check('routing assistant maturity audit script exists', exists('tools/routing-assistant-maturity-audit.js') && pkg.scripts?.['audit:routing-assistant-maturity'] === 'node tools/routing-assistant-maturity-audit.js', 'tools/routing-assistant-maturity-audit.js');
check('routing productization gate exists', exists('tools/routing-product-audit.js') && pkg.scripts?.['audit:routing-product'] === 'node tools/routing-product-audit.js', 'routing productization gate');
check('IPv6/DNS safety audit script exists', exists('tools/ipv6-dns-safety-audit.js') && pkg.scripts?.['audit:ipv6-dns-safety'] === 'node tools/ipv6-dns-safety-audit.js', 'tools/ipv6-dns-safety-audit.js');

const mainRs = readText('src-tauri/src/main.rs');
const coreRuntimeRs = readText('src-tauri/src/core_runtime.rs');
const profileCompilerRs = readText('src-tauri/src/profile_compiler.rs');
const configPipelineRs = readText('src-tauri/src/config_pipeline.rs');
const activeConnectionCommandBody = mainRs.match(/fn active_connection_count\(state: State<AppState>\) -> Result<JsonValue, String> \{([\s\S]*?)\n\}/)?.[1] || '';
const powershellCalls = (mainRs.match(/Command::new\("powershell\.exe"\)/g) || []).length;
check(
  'PowerShell commands are hidden on Windows',
  powershellCalls === 1 &&
    /fn run_powershell[\s\S]*creation_flags\((?:core_runtime::)?CREATE_NO_WINDOW\)/.test(mainRs),
  `${powershellCalls} powershell launcher(s)`,
);

const indexHtml = readText('src/index.html');
const appJs = readText('src/app.js');
const stylesCss = readText('src/styles.css');
const capabilitiesJson = readText('src-tauri/capabilities/default.json');
const interactionSmoke = readText('tools/interaction-smoke.js');
const perfSmoke = readText('tools/perf-smoke.js');
const soakSmoke = readText('tools/soak-smoke.js');
const speedAudit = readText('tools/speed-closure-audit.js');
const stabilityAudit = readText('tools/stability-regression-audit.js');
const backendAudit = readText('tools/backend-audit.js');
const uiText = `${indexHtml}\n${appJs}`;
const pageStyleBlock = stylesCss.match(/\.page\s*\{([\s\S]*?)\n\}/)?.[1] || '';
const statusBody = mainRs.match(/fn status\(&mut self\) -> JsonValue \{([\s\S]*?)\n    \}/)?.[1] || '';
const testNodesBody = appJs.match(/async function testNodes\([^)]*\) \{([\s\S]*?)\n\}/)?.[1] || '';
const speedStart = mainRs.indexOf('fn start_proxy_delay_test');
const speedEnd = mainRs.indexOf('fn test_single_proxy_delay', speedStart);
const speedTestBody = speedStart >= 0 && speedEnd > speedStart ? mainRs.slice(speedStart, speedEnd) : '';

function hasControllerCall(method, timeout) {
  return new RegExp(`controller\\s*\\.\\s*${method}\\(\\s*${timeout}\\s*\\)`).test(mainRs);
}

function hasControllerCallWithArg(method, arg, timeout) {
  return new RegExp(`controller\\s*\\.\\s*${method}\\(\\s*${arg}\\s*,\\s*${timeout}\\s*\\)`).test(mainRs);
}

check('node-flow audit is wired to startup and node page switch', appJs.includes('initializeAppData') && appJs.includes('nodeProfileBtn'), 'initializeAppData/nodeProfileBtn');
check('UI text has no mojibake fragments', !/(�|鈫|鈱|鈼|鈻|鉁|鈬|脳|鏈|鍗|棣欐腐|绛夊緟)/.test(uiText), 'index/app text encoding');
check('sidebar version label matches package version', indexHtml.includes(`id="appVersionLabel" class="brand-version">v${pkg.version}</span>`), `v${pkg.version}`);
check('frontend fallback does not hardcode release version', appJs.includes('defaultAppVersion') && !appJs.includes(`appVersion: '${pkg.version}'`), 'defaultAppVersion');
check('network status shows real LAN IP wording', indexHtml.includes('<dt>局域网 IP</dt><dd id="lanIpState"') && !indexHtml.includes('<dt>内网 IP</dt>') && mainRs.includes('fn is_usable_lan_ip') && mainRs.includes('fn route_lan_ip') && mainRs.includes('fn windows_active_lan_ip') && mainRs.includes('Get-NetIPAddress') && mainRs.includes('lan_ip_filter_accepts_private_addresses_only'), '局域网 IP / usable private LAN IP');
check('Aegos defaults avoid FlClash/Codex port 7890', mainRs.includes('AEGOS_DEFAULT_MIXED_PORT: u16 = 7891') && appJs.includes('const defaultMixedPort = 7891') && !appJs.includes('127.0.0.1:7890'), 'mixed port 7891');
check('settings save rejects proxy port conflicts', mainRs.includes('fn validate_port_settings_snapshot') && mainRs.includes('RESERVED_MIXED_PORTS.contains(&settings.mixed_port)') && mainRs.includes('settings.mixed_port == settings.controller_port') && mainRs.includes('fn rollback_settings_after_failure'), 'settings port transaction');
check('runtime DNS avoids local fake-ip resolver contamination', configPipelineRs.includes('pub(crate) const AEGOS_DNS_LISTEN: &str = "127.0.0.1:1054"') && configPipelineRs.includes('pub(crate) fn harden_runtime_dns') && configPipelineRs.includes('pub(crate) fn runtime_dns_safety_report') && mainRs.includes('"Speed test DNS isolation"') && configPipelineRs.includes('proxy-server-nameserver') && configPipelineRs.includes('https://223.5.5.5/dns-query') && configPipelineRs.includes('https://1.1.1.1/dns-query') && mainRs.includes('runtime_dns_is_isolated_from_local_fake_ip_resolvers'), 'proxy-server-nameserver direct upstream');
check('subscription metadata pseudo nodes are filtered before runtime/speed', mainRs.includes('fn is_subscription_metadata_node_name') && mainRs.includes('fn sanitize_subscription_metadata_nodes') && mainRs.includes('subscription_metadata_nodes_are_removed_before_runtime_and_speed') && speedAudit.includes('speed-test targets exclude airport metadata and fake-ip nodes'), 'Traffic/Expire rows filtered');
check('settings page is grouped with runtime summary', indexHtml.includes('class="settings-layout"') && indexHtml.includes('class="settings-summary-grid"') && indexHtml.includes('id="settingsRuntimeSummary"') && indexHtml.includes('id="settingsReliabilitySummary"') && indexHtml.includes('高级运行时') && appJs.includes('settingsRuntimeSummary') && appJs.includes('settingsReliabilitySummary') && stylesCss.includes('.settings-section') && stylesCss.includes('.settings-summary-grid'), 'settings grouped layout');
check('navigation pages are present', ['home', 'nodes', 'connections', 'routing', 'profiles', 'diagnostics', 'logs', 'settings'].every((page) => indexHtml.includes(`data-page="${page}"`) && indexHtml.includes(`data-page-panel="${page}"`)), 'all primary pages');
check('TUN switch exists in settings UI', indexHtml.includes('id="tunToggle"') && appJs.includes("['tunToggle', 'tunEnabled']"), 'tunToggle');
check('TUN switch exists on home UI', indexHtml.includes('id="tunHomeToggle"') && appJs.includes("['tunHomeToggle', 'tunEnabled']"), 'tunHomeToggle');
check('window remains resizable with narrow inner drag gutters', tauri.app?.windows?.[0]?.resizable === true && !indexHtml.includes('window-edge-frame') && !stylesCss.includes('.window-drag-edge') && indexHtml.includes('class="window-drag-gutters"') && stylesCss.includes('.edge-drag-top') && stylesCss.includes('top: 4px'), `resizable=${tauri.app?.windows?.[0]?.resizable}`);
check('sidebar duplicate profile card is removed', !/<section class="profile">/.test(indexHtml), 'no sidebar profile block');
check('home nodes use table rows', appJs.includes('function renderHomeNodeRow') && appJs.includes("className: `row home-row") && !appJs.includes('class="home-node'), 'home-row renderer');
check('home endpoint line is removed', !indexHtml.includes('id="nodeHost"'), 'no nodeHost line');
check('home drag regions are declared', (indexHtml.match(/data-tauri-drag-region/g) || []).length >= 2, 'titlebar and brand drag regions');
check('duplicate top-left page title is removed', !indexHtml.includes('id="pageTitle"') && !appJs.includes('pageTitleEl') && stylesCss.includes('justify-content: flex-end') && interactionSmoke.includes('duplicate top-left page title still renders'), 'no duplicate titlebar page label');
check('quick actions have one-line subscription and protection controls', (indexHtml.match(/id="quick[A-Za-z]+Btn"/g) || []).length === 6 && indexHtml.includes('id="quickProfileBtn"') && indexHtml.includes('id="quickKillBtn"') && indexHtml.includes('id="profileMenu"') && indexHtml.lastIndexOf('id="profileMenu"') > indexHtml.indexOf('</main>') && !indexHtml.includes('id="quickIpBtn"') && !indexHtml.includes('id="quickTunBtn"') && !indexHtml.includes('id="quickCopyProxyBtn"') && !indexHtml.includes('id="smartRecoverBtn"') && !indexHtml.includes('id="quickModeBtn"') && appJs.includes('function renderQuickProfileMenu') && appJs.includes('function toggleProfileMenu') && appJs.includes("updateSetting('killSwitchEnabled'") && interactionSmoke.includes('manual outbound IP quick action still renders') && interactionSmoke.includes('quick subscription menu did not open') && interactionSmoke.includes('quick subscription menu was covered by another layer'), 'one-line quick subscription/protection menu');
check('quick proxy action is before subscription update', indexHtml.indexOf('id="quickProxyBtn"') > 0 && indexHtml.indexOf('id="quickProxyBtn"') < indexHtml.indexOf('id="quickUpdateSubBtn"'), 'quick action order');
check('2.7 visual system refresh is applied', stylesCss.includes('2.7.0 visual system refresh') && stylesCss.includes('--radius-panel: 8px') && stylesCss.includes('backdrop-filter: blur(18px)') && stylesCss.includes('.quick .action-row') && stylesCss.includes('grid-template-rows: 36px') && stylesCss.includes('repeating-linear-gradient'), 'glass layout/radius/icon refresh');
check('glass icon system replaces text glyph controls', indexHtml.includes('class="aegos-icon icon-home"') && indexHtml.includes('class="metric-icon purple aegos-icon icon-latency"') && indexHtml.includes('class="kill-icon aegos-icon icon-shield"') && appJs.includes('function icon(className)') && appJs.includes("icon('icon-speed')") && stylesCss.includes('2.7.14 icon refresh') && stylesCss.includes('-webkit-mask: var(--icon)') && !indexHtml.includes('<span>SUB</span>'), 'svg mask icon refresh');
check('region filters live with home node table', indexHtml.includes('id="homeRegionRow"') && indexHtml.indexOf('id="homeRegionRow"') > indexHtml.indexOf('class="home-nodes'), 'region-row in home nodes');
check('home node mode filters are present', ['region', 'favorite', 'frequent', 'fixed'].every((mode) => indexHtml.includes(`data-home-mode="${mode}"`)) && indexHtml.indexOf('data-home-mode="region"') < indexHtml.indexOf('data-home-mode="frequent"') && !indexHtml.includes('data-page-jump="nodes"') && !indexHtml.includes('<strong>&#24120;&#29992;&#22320;&#21306;</strong>') && stylesCss.includes('grid-template-columns: repeat(6, minmax(0, 1fr))') && appJs.includes("homeNodeMode = 'region'") && appJs.includes("homeRegionFilter = 'HK'") && appJs.includes("homeRegionFilter: 'HK'") && appJs.includes('compareHomeRows') && !appJs.includes('Number(b[5]) - Number(a[5])') && interactionSmoke.includes('home did not default to Hong Kong region') && interactionSmoke.includes('all nodes shortcut still renders on home') && interactionSmoke.includes('home node row order changed after selection'), 'home node modes');
check('manual fixed nodes are editable and persisted', mainRs.includes('manual_nodes') && mainRs.includes('fn save_manual_node') && mainRs.includes('fn apply_manual_nodes') && mainRs.includes('insert_manual_node_into_config') && indexHtml.includes('id="nodeEditorOverlay"') && indexHtml.includes('id="addFixedNodeBtn"') && appJs.includes("invoke('save_manual_node'") && appJs.includes('collectNodeEditorPayload') && interactionSmoke.includes('fixed node editor did not save through backend command'), 'manual fixed nodes');
check('protocol UI does not display core name', indexHtml.includes('id="protocolState"') && indexHtml.includes('id="protocolMetric"') && !indexHtml.includes('>mihomo<'), 'protocolState/protocolMetric');
check('Rust window controls are wired', ['window_minimize', 'window_toggle_maximize', 'window_close'].every((name) => mainRs.includes(name) && appJs.includes(name)), 'window commands');
check('native window drag ACL is explicit and non-duplicated', capabilitiesJson.includes('core:window:allow-start-dragging') && indexHtml.includes('data-tauri-drag-region') && !appJs.includes('window_start_dragging') && !mainRs.includes('fn window_start_dragging'), 'native drag-region permission');
check('admin relaunch command is wired', mainRs.includes('fn relaunch_as_admin') && indexHtml.includes('id="elevateBtn"') && appJs.includes("invoke('relaunch_as_admin'"), 'relaunch_as_admin');
check('advanced settings save uses one background batch job', mainRs.includes('fn update_settings') && mainRs.includes('updateSettings') && appJs.includes('updateSettingsJob') && interactionSmoke.includes("args.kind === 'updateSettings'"), 'updateSettings');
check('speed tests use background progress commands', mainRs.includes('fn start_proxy_delay_test') && mainRs.includes('fn speed_test_status') && appJs.includes("invoke('start_proxy_delay_test'") && appJs.includes("invoke('speed_test_status'") && interactionSmoke.includes("command === 'start_proxy_delay_test'"), 'async speed test');
check('legacy synchronous speed-test command is removed', !mainRs.includes('fn test_proxy_delays') && !mainRs.includes('test_proxy_delays,') && !interactionSmoke.includes('test_proxy_delays'), 'old lock-heavy speed command must stay removed');
check('home recommendation switch is removed', !indexHtml.includes('id="switchRecommendedBtn"') && !indexHtml.includes('class="recommend-compact"') && !indexHtml.includes('id="recommendedNodeName"') && !stylesCss.includes('.recommend-switch') && !appJs.includes('selectBestProxyJob') && !appJs.includes("runBackgroundJob('selectBestProxy'") && interactionSmoke.includes('recommended switch control still renders'), 'home recommendation switch removed');
check('node switch auto refreshes outbound IP without blocking node switching', appJs.includes('function refreshOutboundIpAfterNodeChange') && appJs.includes("runBackgroundJob('refreshOutboundIp'") && appJs.includes('outboundIpRequestSeq') && appJs.includes('void refreshOutboundIpAfterNodeChange()') && interactionSmoke.includes('node switch did not auto refresh outbound IP'), 'auto outbound IP refresh');
check('smart-mode outbound IP lookup routes through hidden current-node group', mainRs.includes('OUTBOUND_IP_RULE_DOMAINS') && mainRs.includes('AEGOS_OUTBOUND_IP_GROUP') && mainRs.includes('fn upsert_outbound_ip_group') && mainRs.includes('fn sync_outbound_ip_group_selection') && mainRs.includes('fn insert_outbound_ip_rules') && mainRs.includes('DOMAIN,{domain},{target}') && mainRs.includes('outbound_ip_lookup_rules_use_internal_current_node_group'), 'smart-mode outbound IP internal routing');
check('core connect is optimistic and refreshes outbound IP without waiting for IP lookup', appJs.includes("if (kind === 'startCore') void refreshOutboundIpAfterNodeChange()") && appJs.includes('function setButtonBusy') && appJs.includes("button.dataset.busy = busy ? 'true' : ''") && interactionSmoke.includes('connect button did not optimistically show disconnect') && interactionSmoke.includes('first connect did not auto refresh outbound IP'), 'connect optimistic outbound IP');
check('kill switch wording is user friendly', indexHtml.includes('断网保护') && appJs.includes('断网保护') && mainRs.includes('"killSwitchEnabled" =>') && mainRs.includes('Disconnect protection enable failed') && mainRs.includes('Disconnect protection disable failed') && !indexHtml.includes('Kill Switch') && !appJs.includes('Kill Switch') && interactionSmoke.includes('quick kill protection did not update setting'), 'disconnect protection wording');
check('disconnect protection quick action uses backend setting', appJs.includes("updateSetting('killSwitchEnabled'") && mainRs.includes('"killSwitchEnabled" =>') && stylesCss.includes('.kill-icon') && interactionSmoke.includes('quick kill protection did not call backend setting') && interactionSmoke.includes('disconnect protection icon is not using stable css icon'), 'disconnect protection backend setting/icon');
check('disconnect protection verifies firewall state', mainRs.includes('fn firewall_program_path') && mainRs.includes('Invoke-AegosNetsh') && mainRs.includes('advfirewall') && mainRs.includes('Get-NetFirewallRule -DisplayName "$rulePrefix *"') && !mainRs.includes('"group=$group"') && mainRs.includes("DefaultOutboundAction -ne 'Block'") && mainRs.includes('$rules.Count -lt 1') && mainRs.includes('$rules.Count -gt 0') && mainRs.includes('Disconnect protection enable failed') && mainRs.includes('[Console]::OutputEncoding'), 'disconnect protection firewall verification');
check('speed test uses standby core without traffic takeover or proxy switching', testNodesBody.includes("invoke('start_proxy_delay_test'") && !testNodesBody.includes("runBackgroundJob('changeProxy'") && !testNodesBody.includes('selectBestProxyJob') && mainRs.includes('fn start_standby') && mainRs.includes('fn ensure_core_for_delay_test') && mainRs.includes('core_runtime::STANDBY_SPEED_START_MESSAGE') && coreRuntimeRs.includes('pub const STANDBY_SPEED_START_MESSAGE') && mainRs.includes('settings.tun_enabled = false') && mainRs.includes('"trafficTakeover"') && !speedTestBody.includes('change_proxy') && interactionSmoke.includes('speed test triggered a proxy switch') && interactionSmoke.includes('batch speed test triggered a proxy switch') && interactionSmoke.includes('standby speed test triggered the connect job'), 'test only prepares a non-takeover controller and updates delay/recommendation');
check('manual system proxy toggle does not auto-connect', mainRs.includes('System proxy preference enabled; connect before applying Windows proxy takeover') && mainRs.includes('if enable && !self.traffic_takeover') && appJs.includes('待连接') && interactionSmoke.includes('manual system proxy toggle auto-connected traffic takeover'), 'system proxy preference before connection');
check('home quick action row keeps stable height across window heights', stylesCss.includes('2.7.5: keep home controls visually stable across window heights') && stylesCss.includes('--home-quick-row: 72px') && stylesCss.includes('grid-template-rows: 36px') && stylesCss.includes('align-content: center'), 'quick row fixed 72/36 layout');
check('home low-value recommendation metrics are replaced with truthful runtime metrics', indexHtml.includes('id="systemProxyMetric"') && indexHtml.includes('id="upRate"') && indexHtml.includes('id="downRate"') && indexHtml.includes('id="stabilityMetric"') && indexHtml.includes('id="activeConnectionsMetric"') && indexHtml.includes('id="lastTestedMetric"') && indexHtml.includes('id="currentNodeTestBtn"') && !indexHtml.includes('id="tunMetric"') && !indexHtml.includes('id="adminMetric"') && !indexHtml.includes('class="side-card traffic-card"') && appJs.includes("classList.toggle('is-danger'") && appJs.includes('function stabilityInfo') && appJs.includes('function lastTestedText') && appJs.includes("invoke('active_connection_count'") && interactionSmoke.includes('home runtime metrics did not show proxy, traffic, stability, active connection, and test age state'), 'runtime metrics replace duplicate recommendation metrics');
check('home latency refresh and stability visuals stay compact', indexHtml.includes('id="currentNodeTestBtn"') && indexHtml.includes('class="aegos-icon icon-speed"') && !indexHtml.includes('id="currentNodeTestBtn" class="metric-refresh" aria-label="测速当前节点"><span class="aegos-icon icon-refresh"') && appJs.includes('metricClassName') && appJs.includes('metric-stability-high') && stylesCss.includes('.metric-grid strong.metric-stability-high') && stylesCss.includes('background: transparent') && stylesCss.includes('color: #1a9f62') && stylesCss.includes('color: #b77912') && stylesCss.includes('color: #d94343') && interactionSmoke.includes('home stability metric rendered a colored background block') && interactionSmoke.includes('home stability metric did not use dedicated level text class') && interactionSmoke.includes('current node delay refresh did not use a speed icon'), 'home stability is text-only and latency refresh uses speed icon');
check('fake node metrics are removed from node surfaces', indexHtml.includes('<small>稳定性</small>') && indexHtml.includes('<strong id="activeConnectionsMetric">') && indexHtml.includes('<strong id="lastTestedMetric">') && indexHtml.includes('<span>状态</span><span class="row-action-labels"') && !indexHtml.includes('<span>状态</span><span>稳定性</span><span class="row-action-labels"') && !indexHtml.includes('<div class="home-row-head"><span></span><span></span><span>节点名称</span><span>地址</span><span>延迟</span><span>状态</span><span>稳定性</span>') && !indexHtml.includes('<span>丢包率</span>') && !indexHtml.includes('<span>负载</span>') && !indexHtml.includes('<span>地址</span><span>延迟</span><span>稳定性</span><span>负载</span>') && appJs.includes('function stabilityInfo') && appJs.includes('stabilityInfo(currentRow, sourceRows)') && interactionSmoke.includes('node table did not render the expected status column'), 'stability remains only on current node; node/home lists keep status without fake stability');
check(
  'active connection count is lightweight and wired through CoreController',
  coreRuntimeRs.includes('pub fn active_connection_count(&self, timeout_ms: u64)') &&
    coreRuntimeRs.includes('pub fn active_connection_count_snapshot_or_idle(') &&
    coreRuntimeRs.includes('pub fn connections_snapshot(&self, timeout_ms: u64)') &&
    coreRuntimeRs.includes('pub fn connections_snapshot_or_empty(&self, running: bool, timeout_ms: u64)') &&
    coreRuntimeRs.includes('pub fn recent_rule_hits_snapshot(') &&
    coreRuntimeRs.includes('pub fn routing_recent_rule_hits_snapshot_or_empty(&self, running: bool)') &&
    coreRuntimeRs.includes('pub fn recent_rule_hits_from_connections(') &&
    mainRs.includes('fn active_connection_count(state: State<AppState>)') &&
    !mainRs.includes('fn active_connection_count(&self) -> JsonValue') &&
    mainRs.includes('active_connection_count,') &&
    mainRs.includes('controller.home_active_connection_count_snapshot_or_idle(running)') &&
    mainRs.includes('controller.ui_connections_snapshot_or_empty(running)') &&
    mainRs.includes('.routing_recent_rule_hits_snapshot_or_empty(running)') &&
    coreRuntimeRs.includes('pub fn home_active_connection_count_snapshot_or_idle(&self, running: bool)') &&
    coreRuntimeRs.includes('pub fn ui_connections_snapshot_or_empty(&self, running: bool)') &&
    coreRuntimeRs.includes('pub const ROUTING_RECENT_RULES_TIMEOUT_MS') &&
    coreRuntimeRs.includes('pub const ROUTING_RECENT_RULES_LIMIT') &&
    coreRuntimeRs.includes('pub const ACTIVE_CONNECTION_COUNT_TIMEOUT_MS') &&
    coreRuntimeRs.includes('pub const CONNECTIONS_SNAPSHOT_TIMEOUT_MS') &&
    !activeConnectionCommandBody.includes('now_secs') &&
    mainRs.includes('controller.close_connection_for_ui(&id)') &&
    mainRs.includes('controller.close_all_connections_for_ui()') &&
    coreRuntimeRs.includes('pub fn close_connection_for_ui(&self, id: &str)') &&
    coreRuntimeRs.includes('pub fn close_all_connections_for_ui(&self)') &&
    coreRuntimeRs.includes('pub const CLOSE_CONNECTION_TIMEOUT_MS') &&
    coreRuntimeRs.includes('pub const CLOSE_ALL_CONNECTIONS_TIMEOUT_MS') &&
    appJs.includes('function refreshActiveConnectionCount') &&
    appJs.includes("invoke('active_connection_count'") &&
    appJs.includes('setInterval(() => refreshActiveConnectionCount(false), 5000)'),
  'active connection metric',
);
check(
  'proxy controller APIs are typed through CoreController',
  coreRuntimeRs.includes('pub fn proxies_snapshot(&self, timeout_ms: u64)') &&
    coreRuntimeRs.includes('pub fn proxy_groups_snapshot(') &&
    coreRuntimeRs.includes('fn normalize_proxy_item') &&
    coreRuntimeRs.includes('pub fn select_proxy(&self, group: &str, proxy: &str, timeout_ms: u64)') &&
    coreRuntimeRs.includes('pub fn apply_proxy_selection(&self, group: &str, proxy: &str)') &&
    coreRuntimeRs.includes('pub fn apply_auxiliary_proxy_selection(&self, group: &str, proxy: &str)') &&
    coreRuntimeRs.includes('pub fn cleanup_stale_connections_after_selection(&self)') &&
    coreRuntimeRs.includes('pub const PROXY_SELECT_TIMEOUT_MS') &&
    coreRuntimeRs.includes('pub const AUXILIARY_PROXY_SELECT_TIMEOUT_MS') &&
    coreRuntimeRs.includes('pub const STALE_CONNECTION_CLEANUP_TIMEOUT_MS') &&
    coreRuntimeRs.includes('pub fn ui_proxy_groups_snapshot(') &&
    coreRuntimeRs.includes('pub fn ui_proxy_groups_snapshot_or_none(') &&
    coreRuntimeRs.includes('pub const PROXY_GROUPS_SNAPSHOT_TIMEOUT_MS') &&
    coreRuntimeRs.includes('pub fn proxy_delay_with_client(') &&
    coreRuntimeRs.includes('pub fn proxy_delay_result_with_client(') &&
    coreRuntimeRs.includes('pub fn classify_delay_http_failure(') &&
    mainRs.includes('.ui_proxy_groups_snapshot_or_none(running, &[AEGOS_OUTBOUND_IP_GROUP])') &&
    !mainRs.includes('fn controller_proxy_groups_snapshot') &&
    !mainRs.includes('.ui_proxy_groups_snapshot(&[AEGOS_OUTBOUND_IP_GROUP])') &&
    !mainRs.includes('.proxy_groups_snapshot(1200, &[AEGOS_OUTBOUND_IP_GROUP])') &&
    !mainRs.includes('.proxies_snapshot(1200)') &&
    !mainRs.includes('fn normalize_proxy_item') &&
    mainRs.includes('.proxy_delay_result_with_client(client, name, test_url, timeout_ms)') &&
    !mainRs.includes('fn classify_delay_http_failure') &&
    mainRs.includes('.apply_auxiliary_proxy_selection(') &&
    mainRs.includes('.apply_proxy_selection(group, proxy)') &&
    mainRs.includes('.cleanup_stale_connections_after_selection()') &&
    !mainRs.includes('.select_proxy(AEGOS_OUTBOUND_IP_GROUP, &proxy, 1500)') &&
    !mainRs.includes('.select_proxy(group, proxy, 5000)') &&
    !mainRs.includes('.close_connections(1500)') &&
    !mainRs.includes('controller_request(controller_port, secret, "GET", "/proxies"') &&
    !mainRs.includes('http://127.0.0.1:{}/proxies/{}/delay') &&
    !speedTestBody.includes('select_proxy(') &&
    !speedTestBody.includes('change_proxy'),
  'proxy API adapter',
);
check(
  'generic CoreManager controller escape hatch is removed',
  coreRuntimeRs.includes('pub fn version_probe(&self, timeout_ms: u64)') &&
    coreRuntimeRs.includes('pub fn wait_until_ready') &&
    coreRuntimeRs.includes('pub fn process_exit_message') &&
    coreRuntimeRs.includes('pub const READY_REUSE_PROBE_TIMEOUT_MS') &&
    coreRuntimeRs.includes('pub const READY_PROBE_TIMEOUT_MS') &&
    coreRuntimeRs.includes('pub const READY_CHECK_ATTEMPTS') &&
    coreRuntimeRs.includes('pub const READY_RETRY_INTERVAL_MS') &&
    coreRuntimeRs.includes('pub const RUNTIME_RESTART_SETTLE_MS') &&
    coreRuntimeRs.includes('pub fn set_mode(&self, mode: &str, timeout_ms: u64)') &&
    coreRuntimeRs.includes('pub fn apply_mode(&self, mode: &str)') &&
    coreRuntimeRs.includes('pub const MODE_APPLY_TIMEOUT_MS') &&
    mainRs.includes('.wait_until_ready(||') &&
    mainRs.includes('core_runtime::READY_REUSE_PROBE_TIMEOUT_MS') &&
    mainRs.includes('core_runtime::RUNTIME_RESTART_SETTLE_MS') &&
    mainRs.includes('self.core_controller().apply_mode(mode)') &&
    !mainRs.includes('self.core_controller().set_mode(mode, 3000)') &&
    !mainRs.includes('version_probe(900)') &&
    !mainRs.includes('version_probe(300)') &&
    !mainRs.includes('for _ in 0..24') &&
    !mainRs.includes('fn controller(') &&
    !mainRs.includes('fn controller_request(') &&
    !mainRs.includes('self.controller('),
  'typed controller methods only',
);
check('TUN-off connect applies system proxy takeover', mainRs.includes('fn apply_takeover_after_core_ready') && mainRs.includes('|| !self.settings.tun_enabled') && mainRs.includes('self.settings.system_proxy = true;') && mainRs.includes('self.set_system_proxy(true)') && interactionSmoke.includes('connected TUN-off system proxy metric stayed highlighted as disabled'), 'connect without TUN uses Windows system proxy takeover');
check('automatic strategy group warning is wired', indexHtml.includes('id="autoGroupNotice"') && indexHtml.includes('id="lockAutoGroupBtn"') && appJs.includes('function isAutoStrategyGroup') && appJs.includes('function lockAutoGroupJob') && interactionSmoke.includes('automatic strategy group warning did not render'), 'auto strategy warning/lock');
check('node row actions are wired and spaced', mainRs.includes('fn test_single_proxy_delay') && appJs.includes("dataset: { nodeAction: 'test'") && appJs.includes("dataset: { nodeAction: 'edit'") && appJs.includes("dataset: { nodeAction: 'favorite'") && appJs.includes("invoke('test_single_proxy_delay'") && stylesCss.includes('scrollbar-gutter: stable') && stylesCss.includes('116px') && indexHtml.includes('row-action-labels') && interactionSmoke.includes('node row actions are too close to the table edge'), 'row action buttons');
check('node-level diagnostics are linked from failed node tests', mainRs.includes('fn node_diagnostics') && mainRs.includes('fn recent_node_logs') && mainRs.includes('"lastFailure"') && appJs.includes('async function captureNodeDiagnostics') && appJs.includes("invoke('node_diagnostics'") && appJs.includes('Node diagnostics:') && interactionSmoke.includes("command === 'node_diagnostics'"), 'node diagnostics link');
check('soak smoke covers failed node diagnostics', soakSmoke.includes("command === 'node_diagnostics'") && soakSmoke.includes('failed single node test did not capture node diagnostics') && soakSmoke.includes("command === 'test_single_proxy_delay'"), 'soak node diagnostics coverage');
const speedPollMs = Number(appJs.match(/const speedTestPollMs = (\d+);/)?.[1] || 0);
check('speed tests stream completed nodes quickly', mainRs.includes('mpsc::channel') && mainRs.includes('speed_test_phases') && mainRs.includes('Arc::new(client)') && mainRs.includes('speed.recommended = speed_recommendation') && speedPollMs > 0 && speedPollMs <= 300, `incremental speed test results; poll=${speedPollMs}ms`);
check('failed speed tests show structured reasons', mainRs.includes('last_failure_reason') && mainRs.includes('lastFailureReason') && mainRs.includes('DelayTestResult') && coreRuntimeRs.includes('pub fn classify_delay_http_failure') && coreRuntimeRs.includes('controller-delay-error') && appJs.includes('function speedFailureReasonLabel') && appJs.includes('function nodeSpeedNoteInfo') && appJs.includes('className: \'node-note note-bad\'') && indexHtml.includes('<span>状态</span>') && speedAudit.includes('failed speed tests keep a visible structured reason'), 'timeout/DNS/TLS/auth labels');
check('speed test preflight blocks unsafe targets before batch probing', mainRs.includes('fn speed_test_preflight') && mainRs.includes('speed_test_preflight(&targets)') && mainRs.includes('speed_test_preflight_blocks_fake_ip_targets') && speedAudit.includes('speed preflight fails fast on unsafe targets'), 'fake-ip/metadata speed preflight');
check('speed runtime binds outbound to physical adapter when virtual TUN exists', mainRs.includes('fn detect_windows_primary_interface_name') && coreRuntimeRs.includes('fn apply_interface_binding') && coreRuntimeRs.includes('"interface-name"') && mainRs.includes('core_runtime::render_runtime_profile_yaml') && mainRs.includes('flclash|clash|mihomo|aegos|tun|tap|wintun') && coreRuntimeRs.includes('runtime_interface_binding_sets_mihomo_interface_name') && !mainRs.includes('fn apply_runtime_interface_binding_name') && backendAudit.includes('runtime outbound interface avoids nested virtual adapter routing') && speedAudit.includes('runtime outbound avoids FlClash virtual adapter route nesting'), 'avoid nested FlClash/Wintun/TUN routing');
check('speed test polling streams shared results to home and nodes', appJs.includes('async function refreshVisibleNodesForSpeed') && appJs.includes('function applySpeedStatusToNodes') && appJs.includes("target: 'all'") && appJs.includes('applySpeedStatusToNodes(status)') && appJs.includes('await refreshVisibleNodesForSpeed(true)') && interactionSmoke.includes('node page did not receive quick home speed results') && interactionSmoke.includes('home page did not receive node batch speed results'), 'shared home/nodes speed refresh');
check('speed tests use protocol-aware adaptive scheduling', mainRs.includes('fn protocol_concurrency') && mainRs.includes('fn speed_test_phases') && mainRs.includes('protocol_primary_timeout_ms') && mainRs.includes('"tuic" => 8') && mainRs.includes('collect_proxy_targets'), 'protocol-aware speed path');
check('Reality/Hysteria2/TUIC scheduler coverage exists', mainRs.includes('text.contains("reality")') && mainRs.includes('protocol_scheduler_handles_reality_hysteria2_and_tuic_explicitly') && mainRs.includes('protocol_concurrency("hysteria2")') && mainRs.includes('protocol_concurrency("tuic")'), 'advanced protocol scheduler tests');
check('Aegos 2.1 background job model is wired', mainRs.includes('fn start_job') && mainRs.includes('fn job_status') && mainRs.includes('fn cancel_job') && appJs.includes("invoke('start_job'") && appJs.includes("invoke('job_status'") && interactionSmoke.includes("command === 'start_job'") && interactionSmoke.includes('missingJobKinds') && mainRs.includes('updateAllProfiles') && appJs.includes('updateAllProfilesJob') && indexHtml.includes('updateAllProfilesBtn'), 'start_job/job_status');
check('background job center is visible and store-driven', indexHtml.includes('id="jobRows"') && appJs.includes('function rememberJob') && appJs.includes('function renderJobCenter') && appJs.includes('setInterval(() => syncJobCenter(false), 2500)') && appJs.includes('data-job-cancel') && appJs.includes('data-job-retry') && appJs.includes("invoke('cancel_job'") && stylesCss.includes('.job-row'), 'job center');
check('core power operations use background jobs', ['startCore', 'stopCore', 'restartCore'].every((name) => mainRs.includes(name) && appJs.includes(name) && interactionSmoke.includes(name)) && !appJs.includes("invoke('start_core'") && !appJs.includes("invoke('stop_core'") && !appJs.includes("invoke('restart_core'"), 'core power jobs');
check('profile and settings apply through background jobs', ['setActiveProfile', 'removeProfile', 'updateSettings'].every((name) => mainRs.includes(name) && appJs.includes(name) && interactionSmoke.includes(name)) && !appJs.includes("invoke('set_active_profile'") && !appJs.includes("invoke('remove_profile'") && !appJs.includes("invoke('update_settings'"), 'profile/settings jobs');
check('profiles can be renamed through background job', mainRs.includes('fn rename_profile') && mainRs.includes('"renameProfile"') && appJs.includes('data-profile-rename') && appJs.includes('function renameProfileJob') && interactionSmoke.includes('profile rename did not use background job'), 'profile rename');
check('single setting changes use background jobs', mainRs.includes('updateSetting') && appJs.includes("runBackgroundJob('updateSetting'") && interactionSmoke.includes("args.kind === 'updateSetting'") && !appJs.includes("invoke('set_system_proxy'") && !appJs.includes("invoke('update_setting'"), 'updateSetting');
check('mode and proxy switching use background jobs', ['setMode', 'changeProxy'].every((name) => mainRs.includes(name) && appJs.includes(name) && interactionSmoke.includes(name)) && !appJs.includes("invoke('set_mode'") && !appJs.includes("invoke('change_proxy'"), 'mode/proxy jobs');
check('system proxy takeover restores previous Windows proxy', mainRs.includes('struct SystemProxySnapshot') && mainRs.includes('capture_proxy_snapshot_before_takeover') && mainRs.includes('write_windows_proxy_snapshot') && mainRs.includes('shutdown_for_exit') && mainRs.includes('"Windows System Proxy takeover"') && appJs.includes('repairSystemProxyJob') && appJs.includes("runBackgroundJob('repairSystemProxy'") && interactionSmoke.includes('repairSystemProxy'), 'proxy takeover snapshot/repair');
check('core startup failures keep diagnostics visible', mainRs.includes('fn start_failure_message') && mainRs.includes('recent_log_summary') && mainRs.includes('"Recent core logs"') && appJs.includes('lastBackgroundJobError') && appJs.includes("if (isPageActive('logs')) renderLogs()"), 'startup diagnostics');
check('diagnostics page shows severity summary and copyable report', mainRs.includes('"summary"') && mainRs.includes('"nextActions"') && mainRs.includes('"severity"') && indexHtml.includes('id="diagSummary"') && indexHtml.includes('id="copyDiagBtn"') && appJs.includes('function renderDiagnosticSummary') && appJs.includes('function renderDiagnosticRows') && appJs.includes('function diagnosticReportText') && appJs.includes('latestDiagnostics') && stylesCss.includes('.diagnostic-summary') && interactionSmoke.includes('diagnostic severity row did not render'), 'diagnostics severity UI');
check('diagnostics navigation does not auto-run heavy diagnostics', appJs.includes('function renderCachedDiagnostics') && appJs.includes('renderCachedDiagnostics();') && !appJs.includes("page === 'diagnostics' && shouldRefreshPageCache(page)) runDiagnostics") && interactionSmoke.includes('diagnostics page navigation auto-ran heavy diagnostics'), 'diagnostics runs on explicit request');
check('notice bar uses severity colors', appJs.includes('function noticeLevel') && appJs.includes("notice.classList.toggle('is-bad'") && stylesCss.includes('.notice.is-bad') && stylesCss.includes('.notice.is-warn') && stylesCss.includes('.notice.is-info'), 'notice severity colors');
check('logs are categorized, filterable, and exportable', mainRs.includes('category: log_category(level, line).to_string()') && mainRs.includes('category: "core".to_string()') && mainRs.includes('fn export_logs_from_state') && mainRs.includes('export_logs_from_state(&state.logs, &state.app_data)') && mainRs.includes('aegos-logs-') && indexHtml.includes('data-log-filter="core"') && indexHtml.includes('id="exportLogsBtn"') && appJs.includes('let logFilter =') && appJs.includes('function logCategoryLabel') && appJs.includes('function exportLogs') && interactionSmoke.includes('log filters triggered backend calls') && interactionSmoke.includes('log export button did not call export_logs'), 'log taxonomy/filter/export UI');
check('core lifecycle has failed-start cleanup and proxy-preserving restart', mainRs.includes('fn terminate_core_process') && mainRs.includes('core_runtime::TERMINATE_FAILED_STARTUP_MESSAGE') && mainRs.includes('core_runtime::TERMINATE_STOP_MESSAGE') && mainRs.includes('core_runtime::TERMINATE_EXIT_MESSAGE') && mainRs.includes('core_runtime::RUNTIME_DRIFT_RESTART_MESSAGE') && coreRuntimeRs.includes('runtime_lifecycle_messages_are_owned_by_runtime_boundary') && mainRs.includes('fn restart_core_preserving_proxy') && mainRs.includes('fn restore_system_proxy_preference') && mainRs.includes('core.restart_core_preserving_proxy(350)'), 'core lifecycle transaction');
check('profile config preflight is wired', mainRs.includes('fn preflight_runtime_config') && mainRs.includes('core_runtime::preflight_runtime_config') && coreRuntimeRs.includes('pub struct RuntimeConfigPreflightInput') && coreRuntimeRs.includes('pub fn preflight_runtime_config') && mainRs.includes('fn preflight_profile_file') && mainRs.includes('"Profile preflight"') && mainRs.includes('Config preflight passed') && mainRs.includes('Profile switch preflight failed') && mainRs.includes('Profile switch failed and rolled back') && coreRuntimeRs.includes('Config preflight failed: subscription has no usable proxies') && coreRuntimeRs.includes('Config preflight failed: proxy group references missing target(s)') && coreRuntimeRs.includes('Config preflight failed: mixed-port should be') && coreRuntimeRs.includes('runtime_config_preflight_validates_runtime_contract_inside_boundary') && configPipelineRs.includes('pub(crate) fn preflight_profile_source') && profileCompilerRs.includes('config_pipeline::preflight_profile_source(source, profile, settings)'), 'profile preflight');
check('profile preflight allows proxy groups to reference other groups', coreRuntimeRs.includes('proxy_group_name_set') && coreRuntimeRs.includes('proxy_group_name_set.contains(name)') && coreRuntimeRs.includes('"PASS" | "COMPATIBLE"'), 'proxy group references');
check('profile switch hot reloads through Aegos runtime transaction path', mainRs.includes('fn hot_reload_profile') && mainRs.includes('fn patch_profile_file') && mainRs.includes('fn launch_runtime_yaml') && coreRuntimeRs.includes('pub fn write_runtime_profile') && coreRuntimeRs.includes('fn atomic_write_text_confined') && mainRs.includes('core_runtime::write_runtime_profile') && mainRs.includes('aegos-runtime-profile.yaml') && coreRuntimeRs.includes('pub struct CoreRuntimeApplyTransaction') && coreRuntimeRs.includes('pub const CONFIG_FORCE_APPLY_ENDPOINT') && coreRuntimeRs.includes('pub const CONFIG_FORCE_APPLY_TIMEOUT_MS') && coreRuntimeRs.includes('pub const CONFIG_APPLY_VERSION_PROBE_TIMEOUT_MS') && coreRuntimeRs.includes('pub fn apply_runtime_config_path(&self, path: &Path)') && coreRuntimeRs.includes('pub fn config_apply_version_probe(&self)') && coreRuntimeRs.includes('controller.apply_runtime_config_path(&self.runtime_profile_path)') && coreRuntimeRs.includes('controller.config_apply_version_probe()') && !coreRuntimeRs.includes('controller.request("GET", "/version", None, 900)') && mainRs.includes('CoreRuntimeApplyTransaction::new') && mainRs.includes('apply_transaction.apply(&self.core_controller())') && !mainRs.includes('"/configs?force=true"') && mainRs.includes('Profile hot reload failed; falling back to restart'), 'profile hot reload');
check('proxy state model persists selections and resolves group references', mainRs.includes('selected_proxy_map') && mainRs.includes('fn resolve_group_leaf') && mainRs.includes('fn apply_group_resolution') && mainRs.includes('realProxyName') && mainRs.includes('.selected_proxy_map') && mainRs.includes('insert(group.to_string(), proxy.to_string())'), 'selected proxy map/group resolution');
check('digest-based config apply skip is wired through profile compiler', mainRs.includes('mod profile_compiler') && mainRs.includes('mod config_pipeline') && configPipelineRs.includes('pub(crate) fn patch_config') && configPipelineRs.includes('pub(crate) fn patch_direct_profile') && configPipelineRs.includes('pub(crate) fn patch_profile_source') && configPipelineRs.includes('pub(crate) fn patch_speed_test_source') && configPipelineRs.includes('pub(crate) fn speed_test_firewall_ports_from_source') && configPipelineRs.includes('pub(crate) fn preflight_config') && configPipelineRs.includes('pub(crate) fn patch_and_preflight') && configPipelineRs.includes('pub(crate) fn preflight_profile_source') && profileCompilerRs.includes('pub(crate) struct RenderedProfile') && profileCompilerRs.includes('pub(crate) fn compile_profile_file') && profileCompilerRs.includes('pub(crate) fn compile_profile_source') && profileCompilerRs.includes('config_pipeline::preflight_profile_source(source, profile, settings)') && !profileCompilerRs.includes('patch_config_with_settings') && !profileCompilerRs.includes('preflight_runtime_config') && profileCompilerRs.includes('digest: sha256_text(&yaml)') && mainRs.includes('profile_compiler::compile_profile_file(profile, settings)') && mainRs.includes('config_pipeline::preflight_profile_source(source.config, &profile, &settings)') && mainRs.includes('config_pipeline::preflight_profile_source(source.clone(), &profile, &settings)') && mainRs.includes('config_pipeline::patch_profile_source(source, profile, &settings)') && mainRs.includes('config_pipeline::patch_direct_profile(&self.settings)') && mainRs.includes('config_pipeline::speed_test_firewall_ports_from_source(') && !mainRs.includes('config_pipeline::patch_speed_test_source(') && !mainRs.includes('proxy_ports_from_config') && !mainRs.includes('config_pipeline::patch_config(') && !mainRs.includes('config_pipeline::patch_and_preflight(') && !mainRs.includes('config_pipeline::preflight_config(') && !mainRs.includes('let patched = patch_config_with_settings(source, settings, Some(&profile.id))?') && mainRs.includes('runtime_config_digest') && mainRs.includes('Profile apply skipped; unchanged runtime config digest') && mainRs.includes('"skipped": true') && mainRs.includes('runtime_config_digest_is_stable_until_settings_change'), 'digest no-op profile apply');
check('operation scheduler serializes core-changing actions', mainRs.includes('operations: Arc<Mutex<()>>') && mainRs.includes('fn lock_operation_queue') && mainRs.includes('operation_queue_is_exclusive') && ['startCore', 'stopCore', 'restartCore', 'setActiveProfile', 'updateSettings', 'updateSetting', 'setMode', 'changeProxy'].every((name) => mainRs.includes(`"${name}"`)), 'shared operation queue');
check('profile switch diagnostics and local integration coverage exist', mainRs.includes('Profile switch requested:') && mainRs.includes('Profile switch completed:') && mainRs.includes('Profile switch preflight failed for') && mainRs.includes('running_switch_preflight_accepts_two_local_profiles'), 'switch diagnostics/integration');
check('node health and speed recommendation engine is wired without home switch', mainRs.includes('struct NodeHealth') && mainRs.includes('fn update_node_health') && mainRs.includes('fn speed_recommendation') && mainRs.includes('lowLatency') && mainRs.includes('"selectBestProxy"') && !appJs.includes("runBackgroundJob('selectBestProxy'") && interactionSmoke.includes('speed test triggered a proxy switch'), 'health/recommendation engine');
check('speed result confidence stays structured for current-node stability', mainRs.includes('fn speed_result_confidence') && mainRs.includes('fn speed_confidence_summary') && mainRs.includes('"healthConfidence"') && mainRs.includes('"recommendedFresh"') && appJs.includes('function confidenceLabel') && appJs.includes('function stabilityInfo') && appJs.includes('metric-stability-high') && stylesCss.includes('.metric-grid strong.metric-stability-high'), 'speed confidence metadata/current-node UI');
check('subscription source preflight is wired', mainRs.includes('struct ProfileSourceSummary') && mainRs.includes('fn summarize_profile_source') && mainRs.includes('subscription download returned empty content') && mainRs.includes('download_profile_source_url_diagnostic') && mainRs.includes('config_pipeline::preflight_profile_source(source.config, &profile, &settings)') && mainRs.includes('let patched = runtime.config') && mainRs.includes('"runtime-preflight"') && appJs.includes('profile-source-summary'), 'subscription preflight');
check('subscription import failures have actionable diagnostics', mainRs.includes('fn subscription_diagnostic') && mainRs.includes('parse_uri_subscription_source_diagnostic') && mainRs.includes('"unsupported-format"') && mainRs.includes('"unsupported-protocol"') && mainRs.includes('"yaml-parse"') && mainRs.includes('subscription_diagnostics_classify_unsupported_protocols') && pkg.scripts?.['audit:subscription'] === 'node tools/subscription-diagnostics-audit.js', 'subscription diagnostics');
check('protocol capability matrix is explicit', mainRs.includes('const AEGOS_URI_PROTOCOLS') && !mainRs.includes('const MIHOMO_PROXY_TYPES') && coreRuntimeRs.includes('pub const SUPPORTED_PROXY_TYPES') && coreRuntimeRs.includes('pub fn supports_proxy_type') && coreRuntimeRs.includes('pub fn protocol_capabilities_json') && mainRs.includes('core_runtime::protocol_capability_summary') && coreRuntimeRs.includes('protocolCapabilities') && coreRuntimeRs.includes('Config preflight failed: unsupported proxy type(s)') && mainRs.includes('preflight_rejects_core_unsupported_proxy_type') && mainRs.includes('manual_hy2_node_is_normalized_to_hysteria2') && coreRuntimeRs.includes('runtime_protocol_capabilities_normalize_and_report_current_contract'), 'protocol capability matrix');
check('sanitized subscription fixtures are audited', exists('tools/subscription-fixture-audit.js') && pkg.scripts?.['audit:subscription-fixtures'] === 'node tools/subscription-fixture-audit.js' && mainRs.includes('sanitized_subscription_fixtures_parse_without_real_tokens') && mainRs.includes('include_str!("../fixtures/subscriptions/clash-basic.yaml")'), 'subscription fixture regression');
check('node switch preflight is wired', mainRs.includes('fn validate_proxy_selection_from_groups') && mainRs.includes('Node switch preflight failed') && mainRs.includes('Node switch preflight passed') && mainRs.includes('node_switch_preflight_validates_group_and_proxy') && mainRs.includes('validate_proxy_selection_from_groups(&groups, group, proxy)?'), 'node switch preflight');
check('connection closure is returned by core and node switch jobs', mainRs.includes('fn connection_closure(&self) -> JsonValue') && coreRuntimeRs.includes('pub fn connection_status_json(') && coreRuntimeRs.includes('pub fn connection_closure_json(') && coreRuntimeRs.includes('"coreRunning"') && coreRuntimeRs.includes('"systemProxyApplied"') && coreRuntimeRs.includes('"currentNode"') && coreRuntimeRs.includes('"outboundIpKnown"') && coreRuntimeRs.includes('connection_status_and_closure_are_runtime_shaped') && mainRs.includes('core_runtime::connection_status_json(') && mainRs.includes('core_runtime::connection_closure_json(') && !mainRs.includes('fn connection_phase(&self)') && !mainRs.includes('"currentNode".to_string()') && !mainRs.includes('"outboundIpKnown".to_string()') && mainRs.includes('"connection": self.connection_closure()') && mainRs.includes('let connection = core.connection_closure();'), 'connection closure');
check('connection failure classifier is wired', mainRs.includes('fn classify_failure_reason') && mainRs.includes('fn classified_error') && mainRs.includes('failure_reason_classifier_covers_common_connection_failures') && mainRs.includes('return Err(classified_error("Node switch", err));'), 'connection failure classifier');
check('subscription metadata self-heals from profile files', mainRs.includes('fn profile_file_summary') && mainRs.includes('fn repair_profile_metadata') && mainRs.includes('fn public_profiles') && mainRs.includes('metadataStatus') && appJs.includes('function profileSummaryText') && appJs.includes('proxyGroupCount'), 'profile metadata self-heal');
check('subscription import/update rollback is wired', mainRs.includes('Profile import applied but startup failed; rolled back') && mainRs.includes('Profile update applied but startup failed; restored previous subscription') && mainRs.includes('Profile was removed before update completed') && mainRs.includes('let previous_raw = fs::read_to_string(&profile_path).ok()') && mainRs.includes('atomic_write_text_confined(&profile_path, &profile_root, raw)'), 'subscription transaction');
check('Aegos reliability recovery is wired without quick action clutter', mainRs.includes('fn recover_network') && mainRs.includes('fn recover_network(&mut self, force: bool)') && mainRs.includes('reliability_profile_failover') && mainRs.includes('probe_proxy_network') && appJs.includes("recoverNetworkJob") && !indexHtml.includes('id="smartRecoverBtn"') && indexHtml.includes('id="reliabilityAutoToggle"'), 'recover_network settings/backend');
check('recovery suggestions are controlled and same-region aware', mainRs.includes('fn recovery_suggestions') && mainRs.includes('"requiresConfirmation"') && mainRs.includes('"sameRegion"') && mainRs.includes('"suggestions": self.recovery_suggestions(5)') && mainRs.includes('recovery_suggestions_rank_same_region_and_fresh_results'), 'controlled recovery suggestions');
check('click selections use shared optimistic mutation layer', appJs.includes('async function runOptimisticAction') && appJs.includes('function snapshotUiState') && appJs.includes('function restoreUiState') && appJs.includes('applyOptimisticSetting') && appJs.includes('applyOptimisticProfileRemove') && appJs.includes('const uiStore') && appJs.includes('function renderUiState') && interactionSmoke.includes('home region child filter did not become active') && interactionSmoke.includes('profile row did not remove optimistically'), 'shared optimistic interaction feedback');
check('button pending feedback is non-blocking', appJs.includes('function setButtonBusy') && appJs.includes("button.classList.toggle('is-pending', busy)") && appJs.includes("button.setAttribute('aria-busy', busy ? 'true' : 'false')") && appJs.includes("button.dataset.busy = busy ? 'true' : ''") && appJs.includes("if (button?.dataset.busy === 'true') return null;") && !appJs.includes('button.disabled = busy') && stylesCss.includes('button.is-pending') && interactionSmoke.includes('button became disabled during pending feedback'), 'aria-busy/data-busy/is-pending');
check('icon-only busy buttons keep fixed content and size', appJs.includes('function isIconOnlyBusyButton') && appJs.includes("button.matches('.metric-refresh, .row-actions button')") && appJs.includes('options.preserveContent || isIconOnlyBusyButton(button)') && stylesCss.includes('.metric-refresh.is-pending .aegos-icon') && stylesCss.includes('.row-actions button.is-pending .aegos-icon') && stylesCss.includes('@keyframes aegosIconBusySpin') && stylesCss.includes('.metric-refresh') && stylesCss.includes('font-size: 0') && interactionSmoke.includes('current node icon refresh button rendered busy text') && interactionSmoke.includes('node row icon test button rendered busy text'), 'small icon buttons never render pending text or resize');
check('subscription mutations show unified pending rows', appJs.includes('function applyOptimisticProfilePending') && appJs.includes('function applyOptimisticProfilesPending') && appJs.includes('function applyOptimisticProfileImport') && appJs.includes('profilePendingText') && appJs.includes("applyOptimisticProfilePending(id, 'updating')") && appJs.includes("applyOptimisticProfilesPending('updating')") && appJs.includes('applyOptimisticProfileImport(url)') && stylesCss.includes('.list-card.is-pending') && interactionSmoke.includes('profile import did not insert a pending row immediately'), 'subscription pending rows');
check('speed tests do not mark the whole foreground busy', appJs.includes('speedTestStarting') && appJs.includes('function testNodes(button = null)') && appJs.includes('function refreshVisibleNodesForSpeed') && appJs.includes('await refreshVisibleNodesForSpeed(true)') && appJs.includes('if (isSpeedTestActive()) queueNodeRefresh') && appJs.includes("$('#quickTestBtn').onclick = (event) => testNodes(event.currentTarget)") && !appJs.includes("$('#quickTestBtn').onclick = (event) => runButtonAction") && interactionSmoke.includes('home filter switch left rows stuck in testing state after speed test'), 'non-blocking speed test start and final delay refresh');
check('diagnostics button shows detached background-job feedback', appJs.includes('function runDetachedButtonAction') && appJs.includes("runBackgroundJob('diagnostics'") && appJs.includes("$('#runDiagBtn').onclick = (event) => runDetachedButtonAction(event.currentTarget, '诊断中...', () => runDiagnostics())") && interactionSmoke.includes('diagnostics button did not show running feedback') && interactionSmoke.includes('running diagnostics blocked sidebar page switching') && interactionSmoke.includes("'diagnostics'"), 'diagnostic button local busy state');
check('speed testing does not block sidebar page switching', appJs.includes('function testNodes(button = null)') && !appJs.includes("$('#quickTestBtn').onclick = (event) => runButtonAction") && interactionSmoke.includes('speed test blocked sidebar page switching'), 'speed test navigation remains responsive');
check('stability regression audit guards repeated blocker classes', stabilityAudit.includes('legacy synchronous delay command is absent') && stabilityAudit.includes('diagnostics stays explicit, detached, and navigation-safe') && stabilityAudit.includes('profile switching cancels stale speed work') && stabilityAudit.includes('proxy-group references are hidden from ordinary nodes and speed targets'), '2.9.51 stability gate');
check('quick subscription menu toggles without rerender flicker', appJs.includes('function renderQuickProfileMenu(options = {})') && appJs.includes("if (!options.force && !menu.classList.contains('hidden')) return") && appJs.includes("$('#quickProfileBtn')?.addEventListener('pointerdown'") && interactionSmoke.includes('quick subscription menu did not close on second click'), 'quick profile menu stable toggle');
check('subscription switch previews local nodes before verified refresh', mainRs.includes('fn preview_profile_groups') && mainRs.includes('fn profile_proxy_groups_for_profile_snapshot') && mainRs.includes('profile_proxy_groups_for_profile_snapshot(') && appJs.includes('function previewProfileNodes') && appJs.includes("invoke('preview_profile_groups'") && appJs.includes('profilePreviewSeq') && interactionSmoke.includes('quick subscription switch did not request local node preview'), 'optimistic subscription node preview');
check('background refresh yields to foreground and background jobs', appJs.includes('foregroundBusy') && appJs.includes('backgroundJobBusy') && appJs.includes('runForegroundAction') && appJs.includes('runBackgroundJob') && appJs.includes('if (!force && (foregroundBusy > 0 || backgroundJobBusy > 0)) return') && appJs.includes('if (foregroundBusy > 0 || backgroundJobBusy > 0) return;'), 'foreground/background scheduler');
check('sidebar navigation is immediate and deferred-load', appJs.includes('pointerdown') && appJs.includes('schedulePageLoad') && appJs.includes('pageLoadToken') && appJs.includes('renderedPage') && appJs.includes('scheduleRowsRender') && /\.nav\s*\{\s*display:\s*grid;\s*gap:\s*6px;\s*contain:\s*layout paint;/.test(stylesCss), 'deferred nav load');
check('rapid sidebar navigation stress coverage exists', perfSmoke.includes('i < 420') && perfSmoke.includes('finalRapidPage') && perfSmoke.includes('button.click()') && perfSmoke.includes('rapid navigation triggered diagnostics before quiet period'), '420 rapid nav switches');
check('page switching hides inactive pages from layout', pageStyleBlock.includes('position: absolute') && pageStyleBlock.includes('display: none') && stylesCss.includes('.page.active') && stylesCss.includes('display: grid') && appJs.includes('pageNavSettleMs') && appJs.includes('pageCacheState'), 'inactive pages do not participate in layout');
check('large node lists are windowed, debounced, and row-cached', appJs.includes('nodeInitialRenderLimit = 36') && appJs.includes('nodeRenderLimit = 96') && appJs.includes('interactiveNodeRenderLimit') && appJs.includes('interactiveNodeCandidateLimit') && appJs.includes('homeNodeRenderLimit = 8') && appJs.includes('rowRenderSettleMs = 320') && appJs.includes('nodeCandidateLimit') && appJs.includes('nodeRows.length < nodeCandidateLimit') && appJs.includes('const interactiveRender = largeList && (isForegroundHot() || isSpeedTestActive())') && appJs.includes('const nodeVisibleLimit = largeList ? visibleNodeLimit : Math.max(nodeInitialRenderLimit, nodeRows.length)') && appJs.includes('sortNodeRows(nodeRows).slice(0, nodeVisibleLimit)') && appJs.includes('matchingNodeCount') && appJs.includes('nodeRowStaticCache') && appJs.includes('function normalizeNodeItemCached'), 'windowed/cached node rendering');
check('large node index is built lazily for first-screen responsiveness', appJs.includes('eagerNodeIndexLimit') && appJs.includes('function nodeIndexForName') && appJs.includes('rebuildNodeItemIndex(latestGroup?.items || [], selectedNode || latestGroup?.now ||') && appJs.includes('nodeIndexForName(key)'), 'lazy node index');
check('proxy-group references are hidden from ordinary node lists', appJs.includes('function isProxyGroupReferenceItem') && appJs.includes('function isRealProxyNodeItem') && appJs.includes('!isRealProxyNodeItem(item)') && mainRs.includes('fn is_proxy_group_reference_item') && mainRs.includes('speed_targets_skip_proxy_group_references'), 'strategy groups and builtin policies are not rendered as ordinary nodes');
check('delay UI uses 100 ms low-latency threshold', appJs.includes('Number(delay) < 100') && appJs.includes('delay-good') && appJs.includes('delay-bad') && stylesCss.includes('.delay-good') && stylesCss.includes('.delay-bad'), 'delay threshold colors');
check('subscription URI parser is available', mainRs.includes('parse_uri_subscription') && mainRs.includes('base64'), 'URI/base64 subscriptions');
check('TUIC URI subscriptions are supported', mainRs.includes('parse_tuic_uri') && mainRs.includes('line.starts_with("tuic://")'), 'tuic:// parser');
check('modern URI airport protocols are supported', mainRs.includes('fn parse_vless_uri') && mainRs.includes('fn parse_hysteria2_uri') && mainRs.includes('fn parse_anytls_uri') && mainRs.includes('line.starts_with("vless://")') && mainRs.includes('line.starts_with("hysteria2://")') && mainRs.includes('line.starts_with("hy2://")') && mainRs.includes('line.starts_with("anytls://")') && mainRs.includes('parses_modern_uri_subscription_protocols') && appJs.includes("text.includes('anytls')") && indexHtml.includes('value="anytls"'), 'vless/hysteria2/anytls URI parser');
check('traffic stream uses CoreController runtime status snapshot reader', !mainRs.includes('fn traffic_snapshot(&self)') && mainRs.includes('.status_traffic_snapshot_or_idle(running, &self.last_traffic)') && coreRuntimeRs.includes('pub fn traffic_snapshot(&self, timeout_ms: u64)') && coreRuntimeRs.includes('pub fn status_traffic_snapshot(&self)') && coreRuntimeRs.includes('pub fn status_traffic_snapshot_or_idle(') && coreRuntimeRs.includes('pub fn idle_traffic_snapshot()') && coreRuntimeRs.includes('pub const STATUS_TRAFFIC_TIMEOUT_MS') && !mainRs.includes('controller("GET", "/traffic"'), '/traffic snapshot');
check('status heartbeat is lightweight', statusBody.includes('status_traffic_snapshot_or_idle(running, &self.last_traffic)') && statusBody.includes('core_runtime::runtime_status_json') && coreRuntimeRs.includes('pub fn runtime_status_json(') && coreRuntimeRs.includes('"version": JsonValue::Null') && !statusBody.includes('"version": JsonValue::Null') && statusBody.includes('recent_logs(120)') && !statusBody.includes('"/version"') && !statusBody.includes('traffic_snapshot(120)'), 'app_status snapshot');
check('release notes exist for package version', exists(releaseDoc), releaseDoc);
if (exists(releaseDoc)) {
  const notes = releaseNotes;
  check('release notes include verification and artifact hash', notes.includes('## Verification') && notes.includes('## Artifact') && notes.includes('SHA-256'), releaseDoc);
  check('release notes hash matches installer or marks source-only', sourceOnlyRelease || (Boolean(installerSha) && notes.toLowerCase().includes(installerSha.toLowerCase())), installerSha || 'source-only');
}

const result = {
  ok: fail.length === 0,
  failed: fail,
  passed: pass,
  installer: exists(installer) ? {
    path: installer,
    size: fs.statSync(path.join(root, installer)).size,
    sha256: installerSha
  } : null,
  generatedAt: new Date().toISOString()
};

console.log(JSON.stringify(result, null, 2));
process.exit(result.ok ? 0 : 2);
